cc_library(
    name = "atk", 
    hdrs = glob(["includes/**/*.h"]),
    visibility = ["//visibility:public",],
    includes = ["includes"],
    include_prefix = "atk",
    strip_include_prefix = "includes",
)


