cc_library(
    name = "pango", 
    hdrs = glob(["includes/*.h"]),
    visibility = ["//visibility:public",],
    includes = ["includes"],
    include_prefix = "pango",
    strip_include_prefix = "includes",
)

