cc_library(
    name = "gdk", 
    hdrs = glob(["includes/**/*.h"]),
    visibility = ["//visibility:public",],
    includes = ["includes"],
    include_prefix = "gdk",
    strip_include_prefix = "includes",
)


