cc_library(
    name = "gdk-pixbuf", 
    hdrs = glob(["includes/**/*.h"]),
    visibility = ["//visibility:public",],
    includes = ["includes"],
    include_prefix = "gdk-pixbuf",
    strip_include_prefix = "includes",
)

