cc_library(
    name = "gtk",
    hdrs = glob(["includes/**/*.h"]),
    visibility = ["//visibility:public"],
        include_prefix = "gtk",
    includes = ["includes"],
    strip_include_prefix = "includes",

)
